version: '3'
services:
  web:
    image: trafex/php-nginx:2.2.0
    restart: always
    ports:
    - "80:8080"
    volumes:
    - ./app/public:/var/www/html
    - ./app:/var/www
    links:
    - db
    - redis
    environment:
    - DEPLOYMENT=development

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@assw0rd!
      MYSQL_DATABASE: appdb
      MYSQL_USER: appdbuser
      MYSQL_PASSWORD: p@ssw0rd!
    volumes:
    - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - ./data/redis
